colorscheme:
  - blue
  - darkblue
  - default
  - desert
  - delek
  - evening
  - elflord
  - industry
  - koehler
  - morning
  - murphy
  - peachpuff
  - pablo
  - ron
  - shine
  - slate
  - torte
  - zellner
  - molokai
  - jellybeans
  - solarized
  - hybrid
  - railscasts
