# 検証対象から除外するファイル
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tests/*'

# 一行の最大文字数は120文字とする（暫定）
Metrics/LineLength:
  Max: 120

# 日本語コメントを認める
Style/AsciiComments:
  Enabled: false

# メソッドの最大行数
# 10 -> 20
Metrics/MethodLength:
  Max: 20

# 循環的複雑度
# 6 -> 10
Metrics/CyclomaticComplexity:
  Max: 10

# 知覚複雑度
# 6 -> 10
Metrics/PerceivedComplexity:
  Max: 10
