vimrc_dir: "/home/vimfactory/vimstorage"
vimrc_default_path: "/home/vimfactory/vimstorage/default/vimrc"
basic_options_path: "/home/vimfactory/app/vimfactory-web/data/basic_options.yml"
colorscheme_options_path: "/home/vimfactory/app/vimfactory-web/data/colorscheme_options.yml"
plugin_options_path: "/home/vimfactory/app/vimfactory-web/data/plugin_options.yml"
programlang_options_path: "/home/vimfactory/app/vimfactory-web/data/programlang_options.yml"
memcached: "localhost:11211"
