vimrc_dir: "/home/vimfactory/vimrcs"
vimrc_default_path: "/home/vimfactory/vimrcs/vimrc_default"
basic_options_path: "/home/vimfactory/app/vimfactory-web/data/basic_options.yml"
colorscheme_options_path: "/home/vimfactory/app/vimfactory-web/data/colorscheme_options.yml"
programlang_options_path: "/home/vimfactory/app/vimfactory-web/data/programlang_options.yml"
